#!/usr/bin/env bash
# Install the harness pre-commit hook into the given worktree.
#
# Usage:
#   install_worktree_hooks.sh <worktree-path> <touch-surface-allowlist-path>
#
# The installed hook is a thin trampoline that:
#   1. Runs `git diff --check` (whitespace sanity)
#   2. Sources HARNESS_TOUCH_SURFACE_FILE from the env it sets
#   3. Invokes check_touch.py (Python) and check_no_placeholders.sh from this repo

set -euo pipefail

WORKTREE="${1:?usage: install_worktree_hooks.sh <worktree-path> <allowlist>}"
ALLOWLIST="${2:?usage: install_worktree_hooks.sh <worktree-path> <allowlist>}"

if [ ! -d "$WORKTREE/.git" ] && [ ! -f "$WORKTREE/.git" ]; then
    echo "install_worktree_hooks: $WORKTREE is not a git checkout" >&2
    exit 2
fi

# Resolve absolute paths so the hook works regardless of cwd.
ALLOWLIST_ABS=$(cd "$(dirname "$ALLOWLIST")" && pwd)/$(basename "$ALLOWLIST")
HARNESS_LIB=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# `git rev-parse --git-path hooks/pre-commit` resolves the right path whether
# WORKTREE is a primary checkout or a linked worktree (which has a `.git` file
# pointing into the main repo's `.git/worktrees/<name>/`).
HOOK_PATH=$(git -C "$WORKTREE" rev-parse --git-path hooks/pre-commit)
# `git -C <dir>` runs from <dir>, so a relative hook path needs joining manually.
case "$HOOK_PATH" in
    /*) ;;
    *)  HOOK_PATH="${WORKTREE}/${HOOK_PATH}" ;;
esac
HOOK_DIR=$(dirname "$HOOK_PATH")
mkdir -p "$HOOK_DIR"

cat > "$HOOK_PATH" <<HOOK
#!/usr/bin/env bash
# Auto-generated by harness/lib/install_worktree_hooks.sh — do not edit.
set -euo pipefail

export HARNESS_TOUCH_SURFACE_FILE="${ALLOWLIST_ABS}"

# 1. Whitespace sanity.
git diff --check --cached || { echo "pre-commit: whitespace check failed" >&2; exit 1; }

# 2. Touch-surface allowlist.
python3 "${HARNESS_LIB}/check_touch.py"

# 3. Placeholder / stub rejection.
bash "${HARNESS_LIB}/check_no_placeholders.sh"
HOOK

chmod +x "$HOOK_PATH"
echo "installed pre-commit hook: $HOOK_PATH"
